const DEFAULT_LOCALE = 'en';

const uiTexts = {
  en: {
    loginPage: {
      title: 'EasyLink Login',
      subtitle: 'Use your account login ID and password.',
      loginIdLabel: 'Login ID',
      loginIdPlaceholder: 'Enter login ID',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Account password',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      loginRequired: 'Login ID is required.',
      loginSuccess: 'Login success.',
      loginFailed: 'Login failed',
      authenticated: 'Authenticated',
      defaultError: 'Unable to login with provided credentials.',
    },
    reportPage: {
      header: {
        label: 'Reporting',
        title: 'Interactive Report',
        description:
          'Filtered dashboard for status distribution, group bars, and bounded drilldown rows.',
      },
      actions: {
        exportCsv: 'Export CSV',
        exportPdf: 'PDF',
        exportExcel: 'Excel',
        refresh: 'Refresh',
      },
      filters: {
        fromLabel: 'From',
        toLabel: 'To',
        groupLabel: 'Group',
        employeeLabel: 'Employee',
        groupPlaceholder: 'All Allowed Groups',
        employeePlaceholder: 'All Employees',
      },
      charts: {
        pie: {
          title: 'Status Distribution (Pie)',
          emptyState: 'No series data available for current filters.',
          rowsLabel: 'Rows',
          onTime: 'On Time',
          late: 'Late',
          earlyLeave: 'Early Leave',
          anomaly: 'Anomaly',
        },
        bar: {
          title: 'Group Distribution (Bar)',
          emptyState: 'No grouped chart data available for current filters.',
          target: 'Target: {{hours}}h',
          globalConfig: '(global config)',
        },
      },
      drilldown: {
        heading: 'Drilldown Rows',
        showingRows: 'Showing {{count}} rows',
        ofLabel: 'of',
        truncatedSuffix: '(server-capped at {{limit}})',
        emptyState: 'No drilldown rows available for selected filters.',
        loading: 'Loading report...',
        statusPrefix: ' - Status: {{value}}',
        groupPrefix: ' - Group: {{value}}',
        clearFilter: 'Clear Filter',
        pageOf: 'Page {{page}} of {{total}}',
      },
      table: {
        columns: {
          date: 'Date',
          employee: 'Employee',
          group: 'Group',
          status: 'Status',
          flags: 'Flags',
          schedule: 'Schedule',
          actual: 'Actual',
          scans: 'Scans',
          workedHours: 'Worked Hours',
        },
        fallbacks: {
          unknownEmployee: 'Unknown',
          ungrouped: 'Ungrouped',
        },
      },
      errors: {
        forbidden: 'Dashboard access denied',
        requestFailed: 'Report request failed',
        fetchFailed: 'Failed to load report.',
      },
    },
    attendanceShared: {
      previous: 'Previous',
      next: 'Next',
      rows: 'Rows',
      total: 'Total',
      records: 'records',
      anomalies: 'anomalies',
      noData: 'No data in selected range.',
    },
    attendancePage: {
      header: {
        label: 'Records',
        title: 'Employee Attendance',
        description:
          'Raw scanlog linked to employee fullname, group filtering, and late dashboard.',
      },
      errors: {
        loadFailed: 'Could not load attendance data. Please retry.',
        retry: 'Retry',
        groupsFailedTitle: 'Groups unavailable',
        groupsFailedMessage: 'Could not load group list. Group filtering may be limited.',
        holidaysFailedTitle: 'Holidays unavailable',
        holidaysFailedMessage: 'Could not load holiday calendar. Holiday highlighting may be missing.',
      },
      actions: {
        reviewPunches: 'Review Punches',
        exportExcel: 'Export Excel',
        exportCsv: 'Export CSV',
        printPdf: 'Print / PDF',
        exportScopeTitle: 'Choose export scope',
        exportScopeCurrentGroup: 'Current group',
        exportScopeAllGroups: 'All groups',
      },
      tabs: {
        summary: 'Daily Attendance',
        quick_summaries: 'Quick Summaries',
        raw: 'Raw Scanlog',
        dashboard: 'Employee Dashboard',
      },
      filters: {
        from: 'From',
        to: 'To',
        group: 'Group',
        allGroups: 'All groups',
        employee: 'Employee',
        allEmployees: 'All employees',
        incompleteOnly: 'Not complete only',
        rowsPerPage: 'Rows per page',
        resultsSummary: '{{count}} rows · {{anomalies}} anomalies',
        presets: {
          today: 'Today',
          week: 'This Week',
          month: 'This Month',
        },
      },
      roleScope: {
        eyebrow: 'Role Scope',
        title: 'Cumulative Attendance Summary',
        empty: 'Cumulative summary is not available for this range and filter.',
        totalDays: 'Total Days',
        totalScan: 'Total Scan',
        late: 'Late',
        earlyLeave: 'Early Leave',
        reviewed: 'Reviewed',
        pendingReview: 'Pending Review',
        avgDuration: 'Average Duration / Day',
        footer: 'Read-only scope: {{employees}} employee, {{records}} record.',
      },
      prediction: {
        eyebrow: 'Monthly Prediction',
        title: 'Monthly Prediction Context',
        empty: 'Prediction context is not available for this scope.',
        monthTarget: 'Target Month',
        monthlyMinimum: 'Monthly Minimum Hours',
        targetSource: 'Target Source',
        hourSuffix: 'hours',
        mixedWarning: 'This scope has mixed monthly targets across employees.',
      },
      interactive: {
        pieTitle: 'Status Distribution',
        pieRowsLabel: 'Rows',
        pieEmpty: 'No series data available for current filters.',
        barTitle: 'Monthly Minimum Overlay by Group',
        barEmpty: 'No grouped chart data available for current filters.',
        clearDrilldown: 'Clear drilldown',
        mixedTarget: 'mixed target',
        drilldownHeading: 'Drilldown Rows',
        drilldownShowing: 'Showing {{count}} rows of {{total}}.',
        drilldownEmpty: 'No drilldown rows available for selected filters.',
        drilldownStatus: 'Status: {{value}}',
        drilldownGroup: 'Group: {{value}}',
        colDate: 'Date',
        colEmployee: 'Employee',
        colGroup: 'Group',
        colStatus: 'Status',
        colSchedule: 'Schedule',
        colActual: 'Actual',
        colScans: 'Scans',
        targetTooltip: 'Target: {{hours}}h',
      },
      schedulePlanning: {
        eyebrow: 'Schedule Planning',
        title: 'Manage current and upcoming month schedules',
        description: 'Leader scope includes planning and schedule management for current + upcoming month.',
        currentMonth: 'Current Month Plan',
        upcomingMonth: 'Upcoming Month Plan',
        currentMonthTitle: 'Current month planning',
        currentMonthDesc: 'Open group planning grid and manage current month assignments.',
        upcomingMonthEyebrow: 'Upcoming month',
        nextMonthTitle: 'Next month planning',
        nextMonthDesc: 'Prepare upcoming month schedule without opening admin review tools.',
      },
      quickSummaries: {
        description:
          'Employee rows and compact DD + day columns, each cell includes all punch times for that day.',
      },
      raw: {
        retry: 'Retry',
        date: 'Date',
        time: 'Time',
        pin: 'PIN',
        employee: 'Employee Fullname',
        group: 'Group',
        review: 'Review',
        verifyIoWorkcode: 'Verify / IO / Workcode',
        empty: 'No raw scanlog rows in range',
        reviewed: 'Reviewed',
        pending: 'Pending',
      },
      dashboard: {
        title: 'How Many Times Employee Is Late (Top 12)',
        empty: 'No attendance rows in selected range.',
        late: 'Late',
        lateSuffix: 'late',
        group: 'Group',
        anomaly: 'Anomaly',
        earlyLeave: 'Early Leave',
        records: 'Records',
        employee: 'Employee',
        totalRows: 'Total Rows',
      },
      table: {
        date: 'Date',
        name: 'Name',
        group: 'Group',
        shift: 'Shift',
        in: 'In',
        out: 'Out',
        duration: 'Duration',
        status: 'Status',
        review: 'Review',
        note: 'Note',
        loading: 'Loading...',
        noRecords: 'No records in range',
        reviewed: 'Reviewed',
        pending: 'Pending',
        notRequired: 'Not Required',
        schedule: 'Schedule',
        late: 'Late',
        earlyLeave: 'Early Leave',
        noteAction: 'Note',
      },
      pager: {
        showing: 'Showing {{from}}-{{to}} of {{total}}',
      },
      print: {
        title: 'Attendance Print',
        rangeLabel: 'Range',
        dateRangeLabel: 'Date Range',
        groupLabel: 'Group',
        rawTitle: 'Raw Scanlog',
        summaryTitle: 'Daily Attendance',
        totalPunches: 'Total Punches',
        allGroupsFallback: 'All Groups',
      },
      noteModal: {
        title: 'Edit Note',
        status: 'Status',
        noteLabel: 'Note / Remarks',
        notePlaceholder: 'Example: doctor leave, out-of-office assignment...',
        manualHours: 'Manual Hours',
        manualHoursPlaceholder: 'e.g. 8',
        approveOverride: 'Approve manual hours override',
        cancel: 'Cancel',
        save: 'Save',
        saving: 'Saving...',
        saveFailedMessage: 'Failed to save attendance note.',
        saveFailedTitle: 'Unable to save note',
      },
    },
    attendanceReviewPage: {
      header: {
        title: 'Attendance Review',
        description:
          'Punch timeline per employee/day. Compare against shift and normalize accidental double punches.',
      },
      nav: {
        backToAttendance: 'Back to Attendance',
        openSchedule: 'Open Schedule',
      },
      filters: {
        from: 'From',
        to: 'To',
        group: 'Group',
        allGroups: 'All groups',
        apply: 'Apply',
        pin: 'PIN',
        pinPlaceholder: 'Filter PIN',
        anomalyType: 'Anomaly Type',
        quickPreset: {
          today: 'Today',
          thisWeek: 'This Week',
          thisMonth: 'This Month',
          lastMonth: 'Last Month',
        },
        anomalyOptions: {
          late: 'Late',
          earlyLeave: 'Early Leave',
          absent: 'Absent',
          anomaly: 'Anomaly',
        },
      },
      adminProfile: {
        label: 'Admin profile quick-open',
        selectPlaceholder: 'Select employee profile',
        open: 'Open',
      },
      warnings: {
        hiddenTableMigrationPrefix: 'To hide accidental punches, run',
        hiddenTableMigrationSuffix: '.',
      },
      table: {
        date: 'Date',
        employee: 'Employee',
        group: 'Group',
        shift: 'Shift',
        times: 'Times in one cell',
        compareResult: 'Compare Result',
        punchMeta: 'Punch Meta',
        loading: 'Loading review rows...',
        empty: 'No rows for selected range',
        noVisiblePunches: 'No visible punches',
        total: 'Total',
        hidden: 'Hidden',
        reviewPunches: 'Review punches',
        hideDetail: 'Hide detail',
      },
      punchDetail: {
        timelineHint: 'Punch timeline (admin can soft-hide duplicates and apply taxonomy tags)',
        time: 'Time',
        verify: 'Verify',
        io: 'IO',
        sn: 'SN',
        workcode: 'Workcode',
        state: 'State',
        action: 'Action',
        hidden: 'hidden',
        visible: 'visible',
        tag: 'Tag',
        hide: 'Hide',
        unhide: 'Unhide',
        adminOnly: 'admin only',
        reasonPlaceholder: 'reason',
        notePlaceholder: 'note',
      },
      verifyMode: {
        fingerprint: 'Fingerprint',
        faceRecognition: 'Face Recognition',
        veinScan: 'Vein Scan',
        card: 'Card',
        face: 'Face',
        palm: 'Palm',
        fallback: 'Mode',
      },
      ioMode: {
        checkIn: 'Check In',
        checkOut: 'Check Out',
        breakOut: 'Break Out',
        breakIn: 'Break In',
        fallback: 'IO',
      },
      taxonomy: {
        late: 'late',
        acceptable: 'acceptable',
        invalid: 'invalid',
      },
      status: {
        normal: 'normal',
        late: 'terlambat',
        earlyLeave: 'pulang awal',
        absent: 'tidak hadir',
        doublePunch: 'Double Punch',
      },
      actions: {
        refresh: 'Refresh',
      },
    },
    machinePage: {
      header: {
        title: 'Machine Connect',
        description:
          'All machine operations are queued asynchronously through API workers. SDK response references are validated against docs/response_testing.md and docs/scanlog-sdk-curl-postman-reference.md.',
      },
      errors: {
        refreshQueueFailed: 'Failed to refresh machine queue',
        refreshStatusFailed: 'Failed to refresh machine status',
      },
      connection: {
        title: 'Connection Checker',
        refresh: 'Refresh Status',
        checking: 'Checking machine connection...',
        summaryOnline: 'Machine connection is healthy.',
        summaryDegraded: 'Machine connection is partially available.',
        summaryOffline: 'Machine connection is offline.',
        lastChecked: 'Last checked {{time}}',
        source: 'Source: {{source}}',
        notConfigured: 'SDK not configured — set EASYLINK_DEVICE_SN and EASYLINK_WSDK_IP in your .env.',
        statusOnline: 'Online',
        statusDegraded: 'Degraded',
        statusOffline: 'Offline',
        statusChecking: 'Checking',
        statusNotConfigured: 'Not Configured',
        statusOk: 'OK',
        statusFail: 'Failed',
        signalInfo: 'Device info',
        signalTime: 'Device time',
        unknownSource: 'unknown source',
      },
      visibility: {
        employeeSummary:
          'Authenticated employees can see the machine health summary. Admin queue details stay hidden.',
      },
      queue: {
        title: 'Machine Worker Queue',
        refresh: 'Refresh Machine Queue',
        hidden: 'Queue fetch details hidden for non-admin role',
        summary: 'Active {{active}}/{{concurrency}} · Pending {{pending}}',
        queueing: 'Queueing...',
        restricted:
          'Queue fetch status and raw JSON payload are limited to higher-privilege admin users.',
      },
      actions: {
        info: 'Get Device Info',
        time: 'Get Device Time',
        syncTime: 'Sync Device Time',
        pullUsers: 'Pull Users',
        addUser: 'Add User',
        initializeMachine: 'Initialize Machine',
        cancelJob: 'Cancel Job',
        unknown: 'Unknown',
      },
      jobs: {
        title: 'Recent Machine Jobs',
        rows: 'Rows',
        prev: 'Prev',
        next: 'Next',
        total: 'Total',
        empty: 'No machine jobs yet.',
        cancel: 'Cancel',
      },
      common: {
        hiddenForNonAdmin: 'Hidden for non-admin role.',
        unknown: 'unknown',
      },
      confirm: {
        defaultMessage: 'This action will be submitted to background worker queue.',
        queueAction: 'Queue Action',
        initializeTitle: 'Danger: Initialize Machine',
        initializeMessage:
          'Initialization is destructive and can clear users and attendance data from device memory.',
        initializeConfirm: 'Initialize Device',
        cancelJobTitle: 'Cancel Job #{{jobId}}',
        cancelJobMessage:
          'Cancellation is best-effort. Running actions may already be in progress.',
        cancelJobConfirm: 'Cancel Job',
        required: 'Confirmation required before submitting worker action.',
        typePhrase: 'Type exact phrase to continue:',
        phrasePlaceholder: 'Type confirmation phrase',
        cancel: 'Cancel',
      },
      scanlog: {
        queueAllTitle: 'Queue Scanlog All (Paging)',
        queueNewTitle: 'Queue Scanlog New',
        queueAllMessage: 'This can run for a long time and consumes machine paging session.',
        queueNewMessage: 'This will fetch only new scanlog events from SDK and queue ingestion.',
        queueFullPull: 'Queue Full Pull',
        queueNewPull: 'Queue New Pull',
      },
      addUser: {
        menuTitle: 'Add User Menu (SDK /user/set)',
        pinPlaceholder: 'PIN / NIP',
        namePlaceholder: 'Name',
        passwordPlaceholder: 'Password (default 1234)',
        rfidPlaceholder: 'RFID (optional)',
        privilegeUser: 'Privilege 0 - User',
        privilegeAdmin: 'Privilege 1 - Admin',
        queueCta: 'Queue Add User',
        queueBusy: 'Queueing add user...',
        requiredFields: 'PIN and Name are required to queue Add User action.',
        queueTitle: 'Queue Add User to Machine',
        queueMessage: 'This will create or update one machine user via SDK /user/set.',
        queueConfirm: 'Queue Add User',
      },
      task12: {
        actionsTitle: 'Task-12 Parity Actions',
        artifactsTitle: 'Task-12 Artifact Views',
        devinfoTitle: 'Device Info · devinfo alias',
        devinfoBody:
          'Task-12 exposes a devinfo alias for fetching device metadata with artifact output metadata.',
        devinfoQueueTitle: 'Queue Task-12 Device Info (devinfo)',
        devinfoQueueMessage: 'Fetch device info using the Task-12-compatible alias.',
        devinfoQueueConfirm: 'Queue devinfo',
        devinfoQueueBusy: 'Queueing devinfo...',
        devinfoQueueCta: 'Queue devinfo',
        scanlogNewTitle: 'Scanlog New · scanlog_new alias',
        scanlogNewBody: 'Send a Task-12 scanlog_new request with custom window and limit.',
        from: 'From',
        to: 'To',
        limit: 'Limit',
        scanlogNewQueueBusy: 'Queueing scanlog_new...',
        scanlogNewQueueCta: 'Queue scanlog_new',
        usersPartialTitle: 'Stream Users · users_partial alias',
        usersPartialBody: 'Stream paged users from device with delay controls for Task-12 parity.',
        page: 'Page',
        delayMs: 'Delay (ms)',
        usersPartialQueueBusy: 'Queueing users_partial...',
        usersPartialQueueCta: 'Queue users_partial',
        usersPartialStatus: 'Queued page {{page}} with {{delayMs}}ms delay.',
        artifacts: {
          devinfoLabel: 'Device Info (devinfo)',
          devinfoNote: 'Task-12 alias for device info lookup.',
          scanlogNewLabel: 'Scanlog New (scanlog_new)',
          scanlogNewNote: 'Task-12 alias for scanning latest events.',
          usersPartialLabel: 'Stream Users (users_partial)',
          usersPartialNote: 'Task-12 alias for paged user streaming.',
          usersLabel: 'Users (users)',
          usersNote: 'Legacy alias maintained for backward compatibility.',
          empty: 'No artifact yet.',
        },
      },
      controls: {
        scanlogMode: 'Scanlog Mode',
        scanlogModeNew: 'New Scanlog',
        scanlogModeAll: 'All Scanlog (Paging)',
        maxPages: 'Max Pages',
        queueScanlogBusy: 'Queueing scanlog...',
        queueFullScanlogPull: 'Queue Full Scanlog Pull',
        queueNewScanlogPull: 'Queue New Scanlog Pull',
        fullScanlogWarning:
          'Full scanlog paging can run for a long time. Use queue monitor and abort/cancel when needed.',
      },
      dangerZone: {
        title: 'Danger Zone',
        body: 'Initialize Machine can wipe user + attendance + device operational data. Strong confirmation required.',
        queueing: 'Queueing...',
        cta: 'Initialize Machine',
        requiredPhrase: 'Required phrase:',
      },
      results: {
        deviceInfoTitle: 'Device Info Result',
        usersPullTitle: 'Users Pull Result',
        initializeTitle: 'Initialize Result',
        scanlogQueueTitle: 'Scanlog Queue Result',
        noDeviceInfo: 'No device info result yet.',
        noUsersPull: 'No user pull result yet.',
        noInitialize: 'No initialize action executed yet.',
        noScanlogQueue: 'No scanlog sync queued yet.',
        deviceTime: 'Device time: {{time}}',
      },
      row: {
        jobTitle: 'Job #{{id}} · {{action}}',
        created: 'Created {{createdAt}}',
      },
    },
    sidebar: {
      brand: {
        subtitle: 'Attendance',
      },
      sections: {
        overview: 'Overview',
        planning: 'Planning & Attendance',
        master: 'Master Data',
      },
      items: {
        dashboard: 'Dashboard',
        schedule: 'Schedule',
        attendance: 'Attendance',
        attendanceReview: 'Attendance Review',
        performance: 'Performance',
        analytics: 'Analytics',
        report: 'Reports',
        employees: 'Employees',
        groups: 'Groups',
        shifts: 'Shift Maker',
        users: 'Users',
        scanlog: 'Scan Log',
        machine: 'Machine Connect',
      },
      actions: {
        expandSidebar: 'Expand sidebar',
        collapseSidebar: 'Collapse sidebar',
        settings: 'Settings',
        switchToLightMode: 'Switch to light mode',
        switchToDarkMode: 'Switch to dark mode',
        lightMode: 'Light Mode',
        darkMode: 'Dark Mode',
        logout: 'Logout',
      },
      locale: {
        switchToEnglish: 'Switch language to English',
        switchToBahasa: 'Switch language to Bahasa Indonesia',
      },
      roles: {
        admin: 'Admin',
        groupLeader: 'Group Leader',
        member: 'Member',
      },
      version: {
        short: 'v1.2',
        full: 'demo_easylinksdk | v1.2',
      },
    },
    appShell: {
      redirecting: 'Redirecting to login...',
    },
    rightOpsSidebar: {
      title: 'Admin Ops',
      subtitle: 'Queue monitor + review alerts',
      reviewTitle: 'Punch-time reviews',
      reviewHint: 'Rows that need review today',
      reviewAria: 'Punch-time reviews: {{pending}} pending',
      queueSummary: 'Active {{active}}/{{concurrency}} · Pending {{pending}}',
      sections: {
        scanlog: 'Scanlog Queue',
        migration: 'Migration Gates',
        machine: 'Machine Queue',
        preview: 'Admin JSON preview',
      },
      migration: {
        compatibilityFirst: 'Compatibility-first',
        flagOverride: 'Flag override',
        policy: 'policy',
        dataSource: 'data-source',
        machineParity: 'machine parity',
        reporting: 'reporting',
      },
      empty: {
        scanlog: 'No scanlog jobs',
        machine: 'No machine jobs',
      },
      actions: {
        showMore: 'Show more',
        show: 'Show',
        hide: 'Hide',
        refresh: 'Refresh right sidebar',
        expandSidebar: 'Expand right sidebar',
        collapseSidebar: 'Collapse right sidebar',
        closeOverlay: 'Close right sidebar overlay',
      },
      errors: {
        fetchFailed: 'Failed to load ops status',
      },
    },
    dashboardOps: {
      hints: {
        expanded: 'Expanded. Recovery status checks only when requested.',
        collapsed: 'Expand to inspect or trigger the Windows recovery task.',
      },
      actions: {
        expand: 'Expand',
        collapse: 'Collapse',
        checkRecoveryStatus: 'Check Recovery Status',
        openMachinePage: 'Open Machine Page',
        runRecoveryTask: 'Run Recovery Task',
        running: 'Running...',
      },
      labels: {
        taskStatus: 'Task Status',
        healthSummary: 'Health Summary',
      },
      healthSummary: {
        empty: 'No external health summary file is configured or readable yet.',
      },
      errors: {
        loadFailed: 'Failed to load operations status.',
        loadFailedTitle: 'Ops status failed',
      },
      recovery: {
        title: 'Recovery task',
        triggered: 'Recovery task triggered.',
        alreadyRunning: 'Recovery task is already running.',
        triggerFailed: 'Unable to trigger recovery task.',
        triggerFailedTitle: 'Recovery task failed',
      },
      notConfigured: 'Not configured',
    },
    employeesTable: {
      headers: {
        id: 'ID',
        name: 'Full Name (karyawan)',
        relation: 'PIN + Device User (user)',
        nip: 'NIP',
        contract: 'Contract',
        status: 'Link Status',
        duty: 'Active Duty',
      },
      confirmDelete: 'Soft delete {{label}}? This record will be marked deleted.',
      empty: 'No results',
      noName: '- no name set -',
      noUser: '- no user -',
      linked: 'Linked',
      unlinked: 'Unlinked',
      active: 'Active',
      inactive: 'Inactive',
      editAction: 'Edit employee',
      deleteAction: 'Delete employee',
      actions: {
        edit: 'Edit',
        delete: 'Delete',
      },
    },
    groupsList: {
      loading: 'Loading...',
      empty: 'No groups yet. Create one to get started.',
      members: 'members',
      privilege: 'privilege',
      noMembers: 'No members yet. Assign from the selector below.',
      addLabel: 'Add:',
      selectEmployee: '- select employee -',
      leaders: {
        title: 'Group Leaders (shift editor)',
        empty: 'No leaders assigned.',
        selectCandidate: '- select leader candidate -',
      },
      actions: {
        editGroup: 'Edit group',
        deleteGroup: 'Delete group',
        removeLeader: 'Remove leader',
        setLeader: 'Set Leader',
        assign: 'Assign',
        showMoreMembers: 'Show more members',
      },
    },
    shiftsPage: {
      table: {
        loading: 'Loading shifts…',
        empty: 'No shifts found.',
      },
    },
    analyticsPage: {
      bradford: {
        empty: 'No data available',
      },
    },
    performancePage: {
      daily: {
        empty: 'No daily data in selected range.',
      },
      topLate: {
        empty: 'No profile rows for selected range.',
      },
      groupPunch: {
        empty: 'No grouped punch summary data.',
      },
      table: {
        loading: 'Loading dashboard data…',
        empty: 'No performance rows found in selected range.',
      },
    },
    dashboardPage: {
      title: 'Attendance Dashboard',
      stat: {
        totalEmployees: 'Total Employees',
        presentToday: 'Present Today',
        absent: 'Absent',
        late: 'Late',
        activeDevices: 'Active Devices',
      },
      todayHeading: 'Today',
      weeklyTrendHeading: 'Last 7 Days Trend',
      needsReview: 'Needs Review',
      tableHead: { name: 'Name', date: 'Date', issue: 'Issue', action: 'Action' },
      emptyReview: 'No data to review.',
      quickLinks: { attendance: 'Attendance', schedule: 'Schedule', reports: 'Reports' },
      weekdayShort: { sun:'Sun',mon:'Mon',tue:'Tue',wed:'Wed',thu:'Thu',fri:'Fri',sat:'Sat' },
    },
    scanlogPage: {
      title: 'Scan Log',
      description: 'Primary analysis should focus on time, date, PIN, and machine SN. IO mode is shown as reference only.',
      dataSource: 'Data source',
      sourceCanonical: 'Canonical Linux Store',
      sourceLegacy: 'Legacy Scanlog Table',
      refresh: 'Refresh',
      searchPin: 'Search PIN...',
      cols: { date: 'Date', time: 'Time', pin: 'PIN', verify: 'Verify', ioTag: 'IO Tag', workCode: 'Work Code', deviceSn: 'Device SN' },
    },
    employeesPage: {
      eyebrow: 'Management',
      title: 'Employees',
      description: 'Link device users (tb_user) to employee records (tb_karyawan)',
      totalRecords: 'total records',
      addEmployee: 'Add Employee',
      unlinkedOne: 'employee without a real name',
      unlinkedMany: 'employees without a real name',
      unlinkedDesc: 'These users were registered on the device but have not been linked to a full name yet.',
      searchPlaceholder: 'Search name, PIN, or NIP...',
      dutyAll: 'All duty status',
      dutyActive: 'Active duty only',
      dutyInactive: 'Not active duty',
      sortName: 'Sort by name',
      sortPin: 'Sort by PIN',
      sortNip: 'Sort by NIP',
      rows: 'Rows',
      pagerShowing: 'Showing',
      pagerOf: 'of',
      prev: 'Prev',
      next: 'Next',
    },
  },
  id: {
    loginPage: {
      title: 'Login EasyLink',
      subtitle: 'Gunakan ID login dan kata sandi akun Anda.',
      loginIdLabel: 'ID Login',
      loginIdPlaceholder: 'Masukkan ID login',
      passwordLabel: 'Kata Sandi',
      passwordPlaceholder: 'Kata sandi akun',
      signIn: 'Masuk',
      signingIn: 'Sedang masuk...',
      loginRequired: 'ID Login wajib diisi.',
      loginSuccess: 'Login berhasil.',
      loginFailed: 'Login gagal',
      authenticated: 'Telah diautentikasi',
      defaultError: 'Tidak dapat masuk dengan kredensial tersebut.',
    },
    reportPage: {
      header: {
        label: 'Pelaporan',
        title: 'Laporan Interaktif',
        description:
          'Dasbor tersaring untuk distribusi status, batang grup, dan baris drilldown terbatas.',
      },
      actions: {
        exportCsv: 'Ekspor CSV',
        exportPdf: 'PDF',
        exportExcel: 'Excel',
        refresh: 'Muat Ulang',
      },
      filters: {
        fromLabel: 'Dari',
        toLabel: 'Sampai',
        groupLabel: 'Grup',
        employeeLabel: 'Karyawan',
        groupPlaceholder: 'Semua Grup yang Diizinkan',
        employeePlaceholder: 'Semua Karyawan',
      },
      charts: {
        pie: {
          title: 'Distribusi Status (Lingkaran)',
          emptyState: 'Tidak ada data rangkaian untuk filter saat ini.',
          rowsLabel: 'Baris',
          onTime: 'Tepat Waktu',
          late: 'Terlambat',
          earlyLeave: 'Pulang Cepat',
          anomaly: 'Anomali',
        },
        bar: {
          title: 'Distribusi Grup (Batang)',
          emptyState: 'Tidak ada data grafik berkelompok untuk filter saat ini.',
          target: 'Target: {{hours}}j',
          globalConfig: '(konfigurasi global)',
        },
      },
      drilldown: {
        heading: 'Baris Drilldown',
        showingRows: 'Menampilkan {{count}} baris',
        ofLabel: 'dari',
        truncatedSuffix: '(dibatasi server pada {{limit}})',
        emptyState: 'Tidak ada baris drilldown untuk filter yang dipilih.',
        loading: 'Memuat laporan...',
        statusPrefix: ' - Status: {{value}}',
        groupPrefix: ' - Grup: {{value}}',
        clearFilter: 'Hapus Filter',
        pageOf: 'Halaman {{page}} dari {{total}}',
      },
      table: {
        columns: {
          date: 'Tanggal',
          employee: 'Karyawan',
          group: 'Grup',
          status: 'Status',
          flags: 'Penanda',
          schedule: 'Jadwal',
          actual: 'Aktual',
          scans: 'Pemindaian',
          workedHours: 'Jam Kerja',
        },
        fallbacks: {
          unknownEmployee: 'Tidak Diketahui',
          ungrouped: 'Tanpa Grup',
        },
      },
      errors: {
        forbidden: 'Akses dashboard ditolak',
        requestFailed: 'Permintaan laporan gagal',
        fetchFailed: 'Gagal memuat laporan.',
      },
    },
    attendanceShared: {
      previous: 'Sebelumnya',
      next: 'Berikutnya',
      rows: 'Baris',
      total: 'Total',
      records: 'data',
      anomalies: 'anomali',
      noData: 'Tidak ada data pada rentang terpilih.',
    },
    attendancePage: {
      header: {
        label: 'Data',
        title: 'Absensi Karyawan',
        description:
          'Raw scanlog ditautkan ke nama karyawan, filter grup, dan dasbor keterlambatan.',
      },
      errors: {
        loadFailed: 'Gagal memuat data absensi. Silakan coba lagi.',
        retry: 'Coba Lagi',
        groupsFailedTitle: 'Grup tidak tersedia',
        groupsFailedMessage: 'Gagal memuat daftar grup. Filter grup mungkin terbatas.',
        holidaysFailedTitle: 'Hari libur tidak tersedia',
        holidaysFailedMessage: 'Gagal memuat kalender hari libur. Penanda hari libur mungkin hilang.',
      },
      actions: {
        reviewPunches: 'Tinjau Punch',
        exportExcel: 'Ekspor Excel',
        exportCsv: 'Ekspor CSV',
        printPdf: 'Cetak / PDF',
        exportScopeTitle: 'Pilih cakupan ekspor',
        exportScopeCurrentGroup: 'Grup saat ini',
        exportScopeAllGroups: 'Semua grup',
      },
      tabs: {
        summary: 'Absensi Harian',
        quick_summaries: 'Ringkasan Cepat',
        raw: 'Raw Scanlog',
        dashboard: 'Dasbor Karyawan',
      },
      filters: {
        from: 'Dari',
        to: 'Sampai',
        group: 'Grup',
        allGroups: 'Semua grup',
        employee: 'Karyawan',
        allEmployees: 'Semua karyawan',
        incompleteOnly: 'Hanya belum lengkap',
        rowsPerPage: 'Baris per halaman',
        resultsSummary: '{{count}} baris · {{anomalies}} anomali',
        presets: {
          today: 'Hari Ini',
          week: 'Minggu Ini',
          month: 'Bulan Ini',
        },
      },
      roleScope: {
        eyebrow: 'Cakupan Peran',
        title: 'Ringkasan Absensi Kumulatif',
        empty: 'Ringkasan kumulatif tidak tersedia untuk rentang dan filter ini.',
        totalDays: 'Total Hari',
        totalScan: 'Total Scan',
        late: 'Terlambat',
        earlyLeave: 'Pulang Awal',
        reviewed: 'Tereview',
        pendingReview: 'Menunggu Review',
        avgDuration: 'Rata-rata Durasi / Hari',
        footer: 'Cakupan hanya-baca: {{employees}} karyawan, {{records}} data.',
      },
      prediction: {
        eyebrow: 'Prediksi Bulanan',
        title: 'Konteks Prediksi Bulanan',
        empty: 'Konteks prediksi tidak tersedia untuk cakupan ini.',
        monthTarget: 'Bulan Target',
        monthlyMinimum: 'Minimum Jam Bulanan',
        targetSource: 'Sumber Target',
        hourSuffix: 'jam',
        mixedWarning: 'Cakupan ini memiliki variasi target bulanan antar karyawan.',
      },
      interactive: {
        pieTitle: 'Distribusi Status',
        pieRowsLabel: 'Baris',
        pieEmpty: 'Tidak ada data rangkaian untuk filter saat ini.',
        barTitle: 'Overlay Minimum Bulanan per Grup',
        barEmpty: 'Tidak ada data grafik berkelompok untuk filter saat ini.',
        clearDrilldown: 'Hapus drilldown',
        mixedTarget: 'target bervariasi',
        drilldownHeading: 'Baris Drilldown',
        drilldownShowing: 'Menampilkan {{count}} baris dari {{total}}.',
        drilldownEmpty: 'Tidak ada baris drilldown untuk filter yang dipilih.',
        drilldownStatus: 'Status: {{value}}',
        drilldownGroup: 'Grup: {{value}}',
        colDate: 'Tanggal',
        colEmployee: 'Karyawan',
        colGroup: 'Grup',
        colStatus: 'Status',
        colSchedule: 'Jadwal',
        colActual: 'Aktual',
        colScans: 'Pemindaian',
        targetTooltip: 'Target: {{hours}} jam',
      },
      schedulePlanning: {
        eyebrow: 'Perencanaan Jadwal',
        title: 'Kelola jadwal bulan ini dan mendatang',
        description: 'Cakupan leader mencakup perencanaan dan manajemen jadwal untuk bulan ini + mendatang.',
        currentMonth: 'Rencana Bulan Ini',
        upcomingMonth: 'Rencana Bulan Depan',
        currentMonthTitle: 'Perencanaan bulan ini',
        currentMonthDesc: 'Buka grid perencanaan grup dan kelola penugasan bulan berjalan.',
        upcomingMonthEyebrow: 'Bulan mendatang',
        nextMonthTitle: 'Perencanaan bulan depan',
        nextMonthDesc: 'Siapkan jadwal bulan mendatang tanpa membuka alat review admin.',
      },
      quickSummaries: {
        description:
          'Baris karyawan dan kolom DD + hari yang ringkas, setiap sel mencakup seluruh waktu punch pada hari tersebut.',
      },
      raw: {
        retry: 'Coba Lagi',
        date: 'Tanggal',
        time: 'Jam',
        pin: 'PIN',
        employee: 'Nama Lengkap Karyawan',
        group: 'Grup',
        review: 'Review',
        verifyIoWorkcode: 'Verify / IO / Workcode',
        empty: 'Tidak ada baris raw scanlog pada rentang ini',
        reviewed: 'Tereview',
        pending: 'Menunggu',
      },
      dashboard: {
        title: 'Frekuensi Keterlambatan Karyawan (Top 12)',
        empty: 'Tidak ada data absensi pada rentang terpilih.',
        late: 'Terlambat',
        lateSuffix: 'terlambat',
        group: 'Grup',
        anomaly: 'Anomali',
        earlyLeave: 'Pulang Awal',
        records: 'Data',
        employee: 'Karyawan',
        totalRows: 'Total Baris',
      },
      table: {
        date: 'Tanggal',
        name: 'Nama',
        group: 'Grup',
        shift: 'Shift',
        in: 'Masuk',
        out: 'Keluar',
        duration: 'Durasi',
        status: 'Status',
        review: 'Review',
        note: 'Catatan',
        loading: 'Memuat...',
        noRecords: 'Tidak ada data pada rentang ini',
        reviewed: 'Tereview',
        pending: 'Menunggu',
        notRequired: 'Tidak Wajib',
        schedule: 'Jadwal',
        late: 'Terlambat',
        earlyLeave: 'Pulang Awal',
        noteAction: 'Catatan',
      },
      pager: {
        showing: 'Menampilkan {{from}}-{{to}} dari {{total}}',
      },
      print: {
        title: 'Cetak Absensi',
        rangeLabel: 'Rentang',
        dateRangeLabel: 'Rentang tanggal',
        groupLabel: 'Grup',
        rawTitle: 'Raw Scanlog',
        summaryTitle: 'Absensi Harian',
        totalPunches: 'Total Punch',
        allGroupsFallback: 'Semua Grup',
      },
      noteModal: {
        title: 'Edit Catatan',
        status: 'Status',
        noteLabel: 'Catatan / Keterangan',
        notePlaceholder: 'Contoh: izin dokter, tugas luar kota...',
        manualHours: 'Jam Manual',
        manualHoursPlaceholder: 'mis. 8',
        approveOverride: 'Setujui override jam manual',
        cancel: 'Batal',
        save: 'Simpan',
        saving: 'Menyimpan...',
        saveFailedMessage: 'Gagal menyimpan catatan absensi.',
        saveFailedTitle: 'Tidak dapat menyimpan catatan',
      },
    },
    attendanceReviewPage: {
      header: {
        title: 'Tinjauan Absensi',
        description:
          'Linimasa scan per karyawan/hari. Bandingkan dengan shift dan normalkan scan ganda yang tidak disengaja.',
      },
      nav: {
        backToAttendance: 'Kembali ke Absensi',
        openSchedule: 'Buka Jadwal',
      },
      filters: {
        from: 'Dari',
        to: 'Sampai',
        group: 'Grup',
        allGroups: 'Semua grup',
        apply: 'Terapkan',
        pin: 'PIN',
        pinPlaceholder: 'Saring PIN',
        anomalyType: 'Tipe Anomali',
        quickPreset: {
          today: 'Hari Ini',
          thisWeek: 'Minggu Ini',
          thisMonth: 'Bulan Ini',
          lastMonth: 'Bulan Lalu',
        },
        anomalyOptions: {
          late: 'Terlambat',
          earlyLeave: 'Pulang Awal',
          absent: 'Tidak Hadir',
          anomaly: 'Anomali',
        },
      },
      adminProfile: {
        label: 'Buka cepat profil (admin)',
        selectPlaceholder: 'Pilih profil karyawan',
        open: 'Buka',
      },
      warnings: {
        hiddenTableMigrationPrefix: 'Untuk menyembunyikan scan tidak sengaja, jalankan',
        hiddenTableMigrationSuffix: '.',
      },
      table: {
        date: 'Tanggal',
        employee: 'Karyawan',
        group: 'Grup',
        shift: 'Shift',
        times: 'Waktu dalam satu sel',
        compareResult: 'Hasil Perbandingan',
        punchMeta: 'Meta Scan',
        loading: 'Memuat baris tinjauan...',
        empty: 'Tidak ada baris untuk rentang yang dipilih',
        noVisiblePunches: 'Tidak ada scan yang terlihat',
        total: 'Total',
        hidden: 'Tersembunyi',
        reviewPunches: 'Tinjau scan',
        hideDetail: 'Sembunyikan detail',
      },
      punchDetail: {
        timelineHint: 'Linimasa scan (admin dapat menyembunyikan duplikat dan menerapkan tag taksonomi)',
        time: 'Waktu',
        verify: 'Verifikasi',
        io: 'IO',
        sn: 'SN',
        workcode: 'Kode Kerja',
        state: 'Status',
        action: 'Aksi',
        hidden: 'tersembunyi',
        visible: 'terlihat',
        tag: 'Tag',
        hide: 'Sembunyikan',
        unhide: 'Tampilkan',
        adminOnly: 'khusus admin',
        reasonPlaceholder: 'alasan',
        notePlaceholder: 'catatan',
      },
      verifyMode: {
        fingerprint: 'Sidik Jari',
        faceRecognition: 'Pengenalan Wajah',
        veinScan: 'Pindai Vena',
        card: 'Kartu',
        face: 'Wajah',
        palm: 'Telapak',
        fallback: 'Mode',
      },
      ioMode: {
        checkIn: 'Masuk',
        checkOut: 'Keluar',
        breakOut: 'Mulai Istirahat',
        breakIn: 'Selesai Istirahat',
        fallback: 'IO',
      },
      taxonomy: {
        late: 'terlambat',
        acceptable: 'dapat diterima',
        invalid: 'tidak valid',
      },
      status: {
        normal: 'normal',
        late: 'terlambat',
        earlyLeave: 'pulang awal',
        absent: 'tidak hadir',
        doublePunch: 'Scan Ganda',
      },
      actions: {
        refresh: 'Muat Ulang',
      },
    },
    machinePage: {
      header: {
        title: 'Koneksi Mesin',
        description:
          'Semua operasi mesin diantrikan secara asinkron melalui worker API. Referensi respons SDK divalidasi terhadap docs/response_testing.md dan docs/scanlog-sdk-curl-postman-reference.md.',
      },
      errors: {
        refreshQueueFailed: 'Gagal menyegarkan antrean mesin',
        refreshStatusFailed: 'Gagal menyegarkan status mesin',
      },
      connection: {
        title: 'Pemeriksa Koneksi',
        refresh: 'Muat Ulang Status',
        checking: 'Memeriksa koneksi mesin...',
        summaryOnline: 'Koneksi mesin sehat.',
        summaryDegraded: 'Koneksi mesin tersedia sebagian.',
        summaryOffline: 'Koneksi mesin sedang offline.',
        lastChecked: 'Terakhir dicek {{time}}',
        source: 'Sumber: {{source}}',
        notConfigured: 'SDK belum dikonfigurasi — atur EASYLINK_DEVICE_SN dan EASYLINK_WSDK_IP di .env Anda.',
        statusOnline: 'Online',
        statusDegraded: 'Degraded',
        statusOffline: 'Offline',
        statusChecking: 'Memeriksa',
        statusNotConfigured: 'Belum Dikonfigurasi',
        statusOk: 'OK',
        statusFail: 'Gagal',
        signalInfo: 'Info perangkat',
        signalTime: 'Waktu perangkat',
        unknownSource: 'sumber tidak diketahui',
      },
      visibility: {
        employeeSummary:
          'Karyawan yang sudah login dapat melihat ringkasan kesehatan mesin. Detail antrean admin tetap disembunyikan.',
      },
      queue: {
        title: 'Antrian Worker Mesin',
        refresh: 'Segarkan Antrian Mesin',
        hidden: 'Detail pengambilan antrian disembunyikan untuk non-admin',
        summary: 'Aktif {{active}}/{{concurrency}} · Tertunda {{pending}}',
        queueing: 'Mengantrikan...',
        restricted:
          'Status antrean dan payload JSON mentah dibatasi untuk pengguna admin dengan hak lebih tinggi.',
      },
      actions: {
        info: 'Ambil Info Perangkat',
        time: 'Ambil Waktu Perangkat',
        syncTime: 'Sinkronkan Waktu Perangkat',
        pullUsers: 'Tarik Pengguna',
        addUser: 'Tambah Pengguna',
        initializeMachine: 'Inisialisasi Mesin',
        cancelJob: 'Batalkan Job',
        unknown: 'Tidak Diketahui',
      },
      jobs: {
        title: 'Job Mesin Terbaru',
        rows: 'Baris',
        prev: 'Prev',
        next: 'Next',
        total: 'Total',
        empty: 'Belum ada job mesin.',
        cancel: 'Batal',
      },
      common: {
        hiddenForNonAdmin: 'Disembunyikan untuk peran non-admin.',
        unknown: 'tidak diketahui',
      },
      confirm: {
        defaultMessage: 'Aksi ini akan dikirim ke antrean worker latar belakang.',
        queueAction: 'Antrekan Aksi',
        initializeTitle: 'Bahaya: Inisialisasi Mesin',
        initializeMessage:
          'Inisialisasi bersifat destruktif dan dapat menghapus data pengguna serta absensi dari memori perangkat.',
        initializeConfirm: 'Inisialisasi Perangkat',
        cancelJobTitle: 'Batalkan Job #{{jobId}}',
        cancelJobMessage:
          'Pembatalan bersifat best-effort. Aksi yang sudah berjalan mungkin tetap berlanjut.',
        cancelJobConfirm: 'Batalkan Job',
        required: 'Konfirmasi diperlukan sebelum mengirim aksi worker.',
        typePhrase: 'Ketik frasa persis untuk melanjutkan:',
        phrasePlaceholder: 'Ketik frasa konfirmasi',
        cancel: 'Batal',
      },
      scanlog: {
        queueAllTitle: 'Antrekan Semua Scanlog (Paging)',
        queueNewTitle: 'Antrekan Scanlog Baru',
        queueAllMessage: 'Proses ini bisa berjalan lama dan menggunakan sesi paging mesin.',
        queueNewMessage:
          'Ini akan mengambil event scanlog terbaru dari SDK dan mengantrikan ingest.',
        queueFullPull: 'Antrekan Tarik Penuh',
        queueNewPull: 'Antrekan Tarik Baru',
      },
      addUser: {
        menuTitle: 'Menu Tambah Pengguna (SDK /user/set)',
        pinPlaceholder: 'PIN / NIP',
        namePlaceholder: 'Nama',
        passwordPlaceholder: 'Kata sandi (default 1234)',
        rfidPlaceholder: 'RFID (opsional)',
        privilegeUser: 'Privilege 0 - Pengguna',
        privilegeAdmin: 'Privilege 1 - Admin',
        queueCta: 'Antrekan Tambah Pengguna',
        queueBusy: 'Mengantrikan tambah pengguna...',
        requiredFields: 'PIN dan Nama wajib diisi untuk mengantrikan aksi Tambah Pengguna.',
        queueTitle: 'Antrekan Tambah Pengguna ke Mesin',
        queueMessage: 'Ini akan membuat atau memperbarui satu pengguna mesin via SDK /user/set.',
        queueConfirm: 'Antrekan Tambah Pengguna',
      },
      task12: {
        actionsTitle: 'Aksi Paritas Task-12',
        artifactsTitle: 'Tampilan Artefak Task-12',
        devinfoTitle: 'Info Perangkat · alias devinfo',
        devinfoBody:
          'Task-12 menyediakan alias devinfo untuk mengambil metadata perangkat beserta metadata artefak output.',
        devinfoQueueTitle: 'Antrekan Task-12 Info Perangkat (devinfo)',
        devinfoQueueMessage: 'Ambil info perangkat menggunakan alias kompatibel Task-12.',
        devinfoQueueConfirm: 'Antrekan devinfo',
        devinfoQueueBusy: 'Mengantrikan devinfo...',
        devinfoQueueCta: 'Antrekan devinfo',
        scanlogNewTitle: 'Scanlog Baru · alias scanlog_new',
        scanlogNewBody: 'Kirim permintaan Task-12 scanlog_new dengan rentang dan limit kustom.',
        from: 'Dari',
        to: 'Sampai',
        limit: 'Limit',
        scanlogNewQueueBusy: 'Mengantrikan scanlog_new...',
        scanlogNewQueueCta: 'Antrekan scanlog_new',
        usersPartialTitle: 'Streaming Pengguna · alias users_partial',
        usersPartialBody:
          'Streaming pengguna bertahap dari perangkat dengan kontrol jeda untuk paritas Task-12.',
        page: 'Halaman',
        delayMs: 'Jeda (ms)',
        usersPartialQueueBusy: 'Mengantrikan users_partial...',
        usersPartialQueueCta: 'Antrekan users_partial',
        usersPartialStatus: 'Halaman {{page}} diantrikan dengan jeda {{delayMs}}ms.',
        artifacts: {
          devinfoLabel: 'Info Perangkat (devinfo)',
          devinfoNote: 'Alias Task-12 untuk lookup info perangkat.',
          scanlogNewLabel: 'Scanlog Baru (scanlog_new)',
          scanlogNewNote: 'Alias Task-12 untuk memindai event terbaru.',
          usersPartialLabel: 'Streaming Pengguna (users_partial)',
          usersPartialNote: 'Alias Task-12 untuk streaming pengguna bertahap.',
          usersLabel: 'Pengguna (users)',
          usersNote: 'Alias legacy dipertahankan untuk kompatibilitas mundur.',
          empty: 'Belum ada artefak.',
        },
      },
      controls: {
        scanlogMode: 'Mode Scanlog',
        scanlogModeNew: 'Scanlog Baru',
        scanlogModeAll: 'Semua Scanlog (Paging)',
        maxPages: 'Maks Halaman',
        queueScanlogBusy: 'Mengantrikan scanlog...',
        queueFullScanlogPull: 'Antrekan Tarik Scanlog Penuh',
        queueNewScanlogPull: 'Antrekan Tarik Scanlog Baru',
        fullScanlogWarning:
          'Paging scanlog penuh bisa berjalan lama. Gunakan monitor antrean dan hentikan/batalkan bila perlu.',
      },
      dangerZone: {
        title: 'Zona Bahaya',
        body: 'Inisialisasi Mesin dapat menghapus data pengguna + absensi + operasional perangkat. Konfirmasi ketat diperlukan.',
        queueing: 'Mengantrikan...',
        cta: 'Inisialisasi Mesin',
        requiredPhrase: 'Frasa wajib:',
      },
      results: {
        deviceInfoTitle: 'Hasil Info Perangkat',
        usersPullTitle: 'Hasil Tarik Pengguna',
        initializeTitle: 'Hasil Inisialisasi',
        scanlogQueueTitle: 'Hasil Antrean Scanlog',
        noDeviceInfo: 'Belum ada hasil info perangkat.',
        noUsersPull: 'Belum ada hasil tarik pengguna.',
        noInitialize: 'Belum ada aksi inisialisasi yang dijalankan.',
        noScanlogQueue: 'Belum ada sinkronisasi scanlog yang diantrikan.',
        deviceTime: 'Waktu perangkat: {{time}}',
      },
      row: {
        jobTitle: 'Job #{{id}} · {{action}}',
        created: 'Dibuat {{createdAt}}',
      },
    },
    sidebar: {
      brand: {
        subtitle: 'Absensi',
      },
      sections: {
        overview: 'Ringkasan',
        planning: 'Perencanaan & Absensi',
        master: 'Data Master',
      },
      items: {
        dashboard: 'Dasbor',
        schedule: 'Jadwal',
        attendance: 'Absensi',
        attendanceReview: 'Review Absensi',
        performance: 'Performa',
        analytics: 'Analitik',
        report: 'Laporan',
        employees: 'Karyawan',
        groups: 'Grup',
        shifts: 'Pembuat Shift',
        users: 'Pengguna',
        scanlog: 'Log Scan',
        machine: 'Koneksi Mesin',
      },
      actions: {
        expandSidebar: 'Perluas sidebar',
        collapseSidebar: 'Ciutkan sidebar',
        settings: 'Pengaturan',
        switchToLightMode: 'Ganti ke mode terang',
        switchToDarkMode: 'Ganti ke mode gelap',
        lightMode: 'Mode Terang',
        darkMode: 'Mode Gelap',
        logout: 'Keluar',
      },
      locale: {
        switchToEnglish: 'Ganti bahasa ke Inggris',
        switchToBahasa: 'Ganti bahasa ke Bahasa Indonesia',
      },
      roles: {
        admin: 'Admin',
        groupLeader: 'Ketua Grup',
        member: 'Anggota',
      },
      version: {
        short: 'v1.2',
        full: 'demo_easylinksdk | v1.2',
      },
    },
    appShell: {
      redirecting: 'Mengalihkan ke login...',
    },
    rightOpsSidebar: {
      title: 'Operasi Admin',
      subtitle: 'Monitor antrean + peringatan review',
      reviewTitle: 'Review jam punch',
      reviewHint: 'Baris yang perlu ditinjau hari ini',
      reviewAria: 'Review jam punch: {{pending}} tertunda',
      queueSummary: 'Aktif {{active}}/{{concurrency}} · Tertunda {{pending}}',
      sections: {
        scanlog: 'Antrean Scanlog',
        migration: 'Gerbang Migrasi',
        machine: 'Antrean Mesin',
        preview: 'Pratinjau JSON Admin',
      },
      migration: {
        compatibilityFirst: 'Kompatibilitas-utama',
        flagOverride: 'Override flag',
        policy: 'kebijakan',
        dataSource: 'sumber-data',
        machineParity: 'paritas mesin',
        reporting: 'pelaporan',
      },
      empty: {
        scanlog: 'Tidak ada job scanlog',
        machine: 'Tidak ada job mesin',
      },
      actions: {
        showMore: 'Tampilkan lebih banyak',
        show: 'Tampilkan',
        hide: 'Sembunyikan',
        refresh: 'Segarkan sidebar kanan',
        expandSidebar: 'Buka sidebar kanan',
        collapseSidebar: 'Tutup sidebar kanan',
        closeOverlay: 'Tutup overlay sidebar kanan',
      },
      errors: {
        fetchFailed: 'Gagal memuat status operasi',
      },
    },
    dashboardOps: {
      hints: {
        expanded: 'Terbuka. Status recovery hanya dicek saat diminta.',
        collapsed: 'Buka untuk memeriksa atau memicu tugas recovery Windows.',
      },
      actions: {
        expand: 'Buka',
        collapse: 'Tutup',
        checkRecoveryStatus: 'Cek Status Recovery',
        openMachinePage: 'Buka Halaman Mesin',
        runRecoveryTask: 'Jalankan Tugas Recovery',
        running: 'Berjalan...',
      },
      labels: {
        taskStatus: 'Status Tugas',
        healthSummary: 'Ringkasan Kesehatan',
      },
      healthSummary: {
        empty: 'Belum ada berkas ringkasan kesehatan eksternal yang dikonfigurasi atau bisa dibaca.',
      },
      errors: {
        loadFailed: 'Gagal memuat status operasi.',
        loadFailedTitle: 'Status operasi gagal',
      },
      recovery: {
        title: 'Tugas recovery',
        triggered: 'Tugas recovery berhasil dipicu.',
        alreadyRunning: 'Tugas recovery sudah berjalan.',
        triggerFailed: 'Tidak bisa memicu tugas recovery.',
        triggerFailedTitle: 'Tugas recovery gagal',
      },
      notConfigured: 'Belum dikonfigurasi',
    },
    employeesTable: {
      headers: {
        id: 'ID',
        name: 'Nama Lengkap (karyawan)',
        relation: 'PIN + Pengguna Perangkat (user)',
        nip: 'NIP',
        contract: 'Kontrak',
        status: 'Status Tautan',
        duty: 'Tugas Aktif',
      },
      confirmDelete: 'Soft delete {{label}}? Data ini akan ditandai terhapus.',
      empty: 'Tidak ada hasil',
      noName: '- nama belum diatur -',
      noUser: '- belum ada user -',
      linked: 'Tertaut',
      unlinked: 'Belum tertaut',
      active: 'Aktif',
      inactive: 'Nonaktif',
      editAction: 'Ubah karyawan',
      deleteAction: 'Hapus karyawan',
      actions: {
        edit: 'Ubah',
        delete: 'Hapus',
      },

    },
    groupsList: {
      loading: 'Memuat...',
      empty: 'Belum ada grup. Buat grup untuk memulai.',
      members: 'anggota',
      privilege: 'privilege',
      noMembers: 'Belum ada anggota. Tetapkan dari pemilih di bawah.',
      addLabel: 'Tambah:',
      selectEmployee: '- pilih karyawan -',
      leaders: {
        title: 'Leader Grup (editor shift)',
        empty: 'Belum ada leader.',
        selectCandidate: '- pilih kandidat leader -',
      },
      actions: {
        editGroup: 'Ubah grup',
        deleteGroup: 'Hapus grup',
        removeLeader: 'Hapus leader',
        setLeader: 'Set Leader',
        assign: 'Tetapkan',
        showMoreMembers: 'Tampilkan anggota lebih banyak',
      },
    },
    shiftsPage: {
      table: {
        loading: 'Memuat shift…',
        empty: 'Tidak ada shift ditemukan.',
      },
    },
    analyticsPage: {
      bradford: {
        empty: 'Tidak ada data tersedia',
      },
    },
    performancePage: {
      daily: {
        empty: 'Tidak ada data harian pada rentang yang dipilih.',
      },
      topLate: {
        empty: 'Tidak ada data profil pada rentang yang dipilih.',
      },
      groupPunch: {
        empty: 'Tidak ada data ringkasan punch grup.',
      },
      table: {
        loading: 'Memuat data dasbor...',
        empty: 'Tidak ada data performa pada rentang yang dipilih.',
      },
    },
    dashboardPage: {
      title: 'Dashboard Absensi',
      stat: {
        totalEmployees: 'Total Karyawan',
        presentToday: 'Hadir Hari Ini',
        absent: 'Tidak Hadir',
        late: 'Terlambat',
        activeDevices: 'Perangkat Aktif',
      },
      todayHeading: 'Hari Ini',
      weeklyTrendHeading: 'Tren 7 Hari Terakhir',
      needsReview: 'Perlu Ditinjau',
      tableHead: { name: 'Nama', date: 'Tanggal', issue: 'Masalah', action: 'Aksi' },
      emptyReview: 'Tidak ada data yang perlu ditinjau.',
      quickLinks: { attendance: 'Absensi', schedule: 'Jadwal', reports: 'Laporan' },
      weekdayShort: { sun:'Min',mon:'Sen',tue:'Sel',wed:'Rab',thu:'Kam',fri:'Jum',sat:'Sab' },
    },
    scanlogPage: {
      title: 'Log Scan',
      description: 'Analisis utama fokus pada waktu, tanggal, PIN, dan SN mesin. Mode IO ditampilkan hanya sebagai referensi.',
      dataSource: 'Sumber data',
      sourceCanonical: 'Penyimpanan Kanonik Linux',
      sourceLegacy: 'Tabel Scanlog Legacy',
      refresh: 'Muat Ulang',
      searchPin: 'Cari PIN...',
      cols: { date: 'Tanggal', time: 'Waktu', pin: 'PIN', verify: 'Verifikasi', ioTag: 'Tag IO', workCode: 'Kode Kerja', deviceSn: 'SN Perangkat' },
    },
    employeesPage: {
      eyebrow: 'Manajemen',
      title: 'Karyawan',
      description: 'Tautkan pengguna perangkat (tb_user) ke catatan karyawan (tb_karyawan)',
      totalRecords: 'total catatan',
      addEmployee: 'Tambah Karyawan',
      unlinkedOne: 'karyawan tanpa nama lengkap',
      unlinkedMany: 'karyawan tanpa nama lengkap',
      unlinkedDesc: 'Pengguna ini terdaftar di perangkat namun belum ditautkan ke nama lengkap.',
      searchPlaceholder: 'Cari nama, PIN, atau NIP...',
      dutyAll: 'Semua status dinas',
      dutyActive: 'Hanya dinas aktif',
      dutyInactive: 'Bukan dinas aktif',
      sortName: 'Urutkan berdasarkan nama',
      sortPin: 'Urutkan berdasarkan PIN',
      sortNip: 'Urutkan berdasarkan NIP',
      rows: 'Baris',
      pagerShowing: 'Menampilkan',
      pagerOf: 'dari',
      prev: 'Sebelum',
      next: 'Berikut',
    },
  },
};

function resolveLocale(locale) {
  if (!locale) return DEFAULT_LOCALE;
  const normalized = String(locale).trim().toLowerCase();
  if (!normalized) return DEFAULT_LOCALE;
  if (uiTexts[normalized]) return normalized;
  const [primary] = normalized.split(/[-_]/);
  return primary && uiTexts[primary] ? primary : DEFAULT_LOCALE;
}

function getNestedValue(object, path) {
  return path.reduce(
    (current, segment) =>
      current && Object.prototype.hasOwnProperty.call(current, segment)
        ? current[segment]
        : undefined,
    object
  );
}

function getUIText(path, locale = DEFAULT_LOCALE) {
  if (!path) return '';
  const trimmedPath = String(path).trim();
  if (!trimmedPath) return '';
  const segments = trimmedPath.split('.');
  const resolvedLocale = resolveLocale(locale);
  const localeValue = getNestedValue(uiTexts[resolvedLocale], segments);
  if (localeValue != null) return localeValue;
  if (resolvedLocale !== DEFAULT_LOCALE) {
    const fallbackValue = getNestedValue(uiTexts[DEFAULT_LOCALE], segments);
    if (fallbackValue != null) return fallbackValue;
  }
  return trimmedPath;
}

export { uiTexts, getUIText };
